# Generated by Django 3.0.2 on 2020-01-09 04:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.AutoField(primary_key=True, serialize=False)),
                ('story_author', models.CharField(max_length=50)),
                ('story_title', models.CharField(max_length=50)),
                ('story_type', models.IntegerField(choices=[(0, 'Event'), (1, 'Blog'), (2, 'Image Gallery')], default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('story_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sayoneuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(5)])),
                ('mailid', models.EmailField(max_length=70)),
                ('username', models.CharField(max_length=70)),
                ('password', models.CharField(max_length=30)),
                ('cnf_pass', models.CharField(max_length=30)),
                ('profile_pic', models.ImageField(upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sayone_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='images')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_story', to='sayonestories.Story')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_pic', models.ImageField(upload_to='images')),
                ('blog_description', models.CharField(max_length=200)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_story', to='sayonestories.Story')),
            ],
        ),
    ]
