# Generated by Django 3.0.2 on 2020-01-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sayonestories', '0002_auto_20200114_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sayoneuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default_pic.jpg', null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('story_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sayonestories.Story')),
                ('user_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
