# Generated by Django 3.0.2 on 2020-01-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayonestories', '0003_auto_20200114_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
        migrations.AddField(
            model_name='story',
            name='story_likes',
            field=models.IntegerField(default=0),
        ),
    ]
