# Generated by Django 2.0.2 on 2020-01-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayonestories', '0005_multipics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='multipics',
        ),
    ]
